version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: type-form-builder-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - type-form-builder-db-data:/var/lib/postgresql/data

volumes:
  type-form-builder-db-data:
